INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ('Puré de papaya', 'Puré de coliflor y patata');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ('Puré de habas y zanahoria', 'Puré de garbanzos y espinacas');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ('Puré de coliflor', 'Puré de alcachofas');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ('Puré de pollo y patata', 'Puré de champiñones y pollo');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ('Puré de papaya', 'Puré de gambas y espinacas');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ('Puré de mandarina', 'Puré de salmón y brócoli');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ('Puré de habas y patata', 'Puré de gambas');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ('Puré de pera y melocotón', 'Puré de zanahoria');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ('Puré de pomelo', 'Puré de bacalao');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de gambas y espinacas', 'Puré de champiñones');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de champiñones y pollo', 'Puré de guisantes');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de habas y zanahoria', 'Puré de papaya');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de ternera y zanahoria', 'Puré de naranja');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pollo', 'Puré de ternera');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de guisantes', 'Puré de fresas y plátano');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de champiñones y patata', 'Puré de piña');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de tomate y arroz', 'Puré de ternera y patatas');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de gambas', 'Puré de ternera');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de manzana y melocotón', 'Puré de manzana y melocotón');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de naranja', 'Puré de champiñones y pollo');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de fresas y plátano', 'Puré de champiñones');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de piña', 'Puré de pera y melocotón');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de manzana', 'Puré de habas y zanahoria');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de habas y zanahoria', 'Puré de garbanzos y espinacas');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de lentejas y arroz', 'Puré de salmón y arroz');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de espinacas', 'Puré de coliflor');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de habas', 'Puré de garbanzos');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de bacalao', 'Puré de ternera y patatas');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de ternera y zanahoria', 'Puré de fresas y plátano');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pollo', 'Puré de lentejas y zanahoria');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de merluza', 'Puré de fresas y mango');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de salmón y brócoli', 'Puré de naranja');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pera y melocotón', 'Puré de lentejas');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de sandía', 'Puré de habas');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de remolacha', 'Puré de manzana y pera');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de brócoli', 'Puré de champiñones');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pavo y zanahoria', 'Puré de garbanzos');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de ternera y patatas', 'Puré de pollo y brócoli');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de garbanzos y espinacas', 'Puré de calabacín');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pollo y patata', 'Puré de habas y zanahoria');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de patata', 'Puré de pavo');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de fresas y mango', 'Puré de pera y melocotón');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de gambas y espinacas', 'Puré de coliflor y brócoli');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de ternera y patatas', 'Puré de papaya');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de salmón y espinacas', 'Puré de merluza');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de melocotón y piña', 'Puré de piña y melocotón');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de coliflor y brócoli', 'Puré de salmón y arroz');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pomelo', 'Puré de fresas y mango');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de judías verdes', 'Puré de champiñones y pollo');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de fresas', 'Puré de melocotón y piña');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de naranja', 'Puré de plátano');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de habas y patata', 'Puré de bacalao');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pollo y verduras', 'Puré de tomate y arroz');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pavo', 'Puré de tomate y arroz');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pera y melocotón', 'Puré de guisantes');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de salmón y arroz', 'Puré de salmón y brócoli');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de calabacín', 'Puré de coliflor y brócoli');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pomelo', 'Puré de lentejas');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de habas', 'Puré de mango y piña');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pomelo', 'Puré de lentejas');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de garbanzos y calabacín', 'Puré de garbanzos y calabacín');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de ternera y zanahoria', 'Puré de pollo y patata');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pavo', 'Puré de lentejas');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de guisantes', 'Puré de lentejas y arroz');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de zanahoria', 'Puré de pavo y zanahoria');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de garbanzos y calabacín', 'Puré de mango y papaya');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de piña y melocotón', 'Puré de champiñones');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de salmón', 'Puré de alcachofas');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de gambas', 'Puré de pollo y patata');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de ternera y patatas', 'Puré de manzana');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de plátano', 'Puré de pollo y brócoli');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de zanahoria', 'Puré de coliflor y patata');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pavo', 'Puré de manzana y piña');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pomelo', 'Puré de salmón');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de ternera y zanahoria', 'Puré de fresas y plátano');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de salmón y arroz', 'Puré de garbanzos y espinacas');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de melón', 'Puré de garbanzos y calabacín');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de judías verdes y pollo', 'Puré de fresas y plátano');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de lentejas y arroz', 'Puré de champiñones y patata');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de judías verdes', 'Puré de salmón y espinacas');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de brócoli', 'Puré de lentejas y arroz');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de calabacín', 'Puré de manzana');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de bacalao', 'Puré de fresas');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pavo y zanahoria', 'Puré de fresas y mango');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pera', 'Puré de habas y patata');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de gambas y espinacas', 'Puré de ternera y patatas');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pavo y zanahoria', 'Puré de zanahoria');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de brócoli', 'Puré de garbanzos y espinacas');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de gambas y espinacas', 'Puré de zanahoria');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de habas', 'Puré de champiñones');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de guisantes', 'Puré de garbanzos y calabacín');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pavo', 'Puré de fresas y plátano');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de ternera', 'Puré de coliflor y patata');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de guisantes', 'Puré de gambas y espinacas');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pavo', 'Puré de pera y melocotón');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de gambas', 'Puré de ternera');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pollo', 'Puré de ternera');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de brócoli', 'Puré de pollo y patata');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de garbanzos y calabacín', 'Puré de pollo y brócoli');
INSERT INTO Menu (platoPrincipal, segundoPlato) VALUES ( 'Puré de pavo y zanahoria', 'Puré de merluza');

ALTER SEQUENCE hibernate_sequence RESTART WITH 1000;
